# **Pipeline d'entraînement avec MLflow**
**Modèles à entraîner**
1. microsoft/Phi-3.5-mini-instruct (phi-3.5-3.8B)
2. meta-llama/Llama-3.2-3B-Instruct (llama-3.2-3B)

## **Installation des dépendances `MLflow` avec `DagsHub`**

In [6]:
!pip install transformers==4.45.0 torch==2.5.0 torchvision==0.20.0

WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Collecting transformers==4.45.0
  Using cached transformers-4.45.0-py3-none-any.whl.metadata (44 kB)
Collecting torch==2.5.0
  Using cached torch-2.5.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Requirement already satisfied: torchvision==0.20.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.20.0)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (3.20.3)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.45.0)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (2026.2.28)
Requirement already satisfied: requests in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (2.32.5)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.45.0)
  Using cached tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers==4.45.0) (4.67.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (4.15.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (3.1.6)
Requirement already satisfied: fsspec in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (2026.1.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch==2.5.0)
  Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch==2.5.0)
  Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch==2.5.0)
  Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (9.1.0.70)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch==2.5.0)
  Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch==2.5.0)
  Using cached nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch==2.5.0)
  Using cached nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch==2.5.0)
  Using cached nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch==2.5.0)
  Using cached nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch==2.5.0)
  Using cached nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch==2.5.0)
  Using cached nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch==2.5.0)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.1.0 (from torch==2.5.0)
  Using cached triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.5.0) (80.10.2)
Collecting sympy==1.13.1 (from torch==2.5.0)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torchvision==0.20.0) (12.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.5.0) (1.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.0) (1.4.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch==2.5.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers==4.45.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers==4.45.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers==4.45.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->transformers==4.45.0) (2026.1.4)
Using cached transformers-4.45.0-py3-none-any.whl (9.9 MB)
Using cached torch-2.5.0-cp312-cp312-manylinux1_x86_64.whl (906.4 MB)
Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
Using cached nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
Using cached nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
Using cached nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
Using cached nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
Using cached nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
Using cached nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Using cached triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Installing collected packages: triton, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.0.0
    Uninstalling triton-3.0.0:
      Successfully uninstalled triton-3.0.0
  Attempting uninstall: sympy━━━━━━━━━━━━━━━━━━━  0/17 [triton]
    Found existing installation: sympy 1.14.0[0m  0/17 [triton]
    Uninstalling sympy-1.14.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/17 [sympy]
      Successfully uninstalled sympy-1.14.0━━━━━━━━━━━━━━━━━━━━━━━  1/17 [sympy]
  Attempting uninstall: nvidia-nvtx-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  1/17 [sympy]
    Found existing installation: nvidia-nvtx-cu12 12.1.105━━━━  1/17 [sympy]
    Uninstalling nvidia-nvtx-cu12-12.1.105:━━━━━━━━━━━━━━━━━━━  1/17 [sympy]
      Successfully uninstalled nvidia-nvtx-cu12-12.1.105━━━━━━  1/17 [sympy]
  Attempting uninstall: nvidia-nvjitlink-cu12━━━━━━━━━━━━━━━━━  1/17 [sympy]
    Found existing installation: nvidia-nvjitlink-cu12 12.8.93  1/17 [sympy]
    Uninstalling nvidia-nvjitlink-cu12-12.8.93:━━━━━━━━━━━━━━━  1/17 [sympy]
      Successfully uninstalled nvidia-nvjitlink-cu12-12.8.93━━  1/17 [sympy]
  Attempting uninstall: nvidia-nccl-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  3/17 [nvidia-nvjitlink-cu12]
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/17 [nvidia-nvjitlink-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-nccl-cu12 2.20.5
    Uninstalling nvidia-nccl-cu12-2.20.5:━━━━━━━━━━━━━━━━━━━━━  3/17 [nvidia-nvjitlink-cu12]
      Successfully uninstalled nvidia-nccl-cu12-2.20.5━━━━━━━━  3/17 [nvidia-nvjitlink-cu12]
  Attempting uninstall: nvidia-curand-cu12━━━━━━━━━━━━━━━━━━━━━━━━  4/17 [nvidia-nccl-cu12]]
    Found existing installation: nvidia-curand-cu12 10.3.2.106  4/17 [nvidia-nccl-cu12]
    Uninstalling nvidia-curand-cu12-10.3.2.106:━━━━━━━━━━━━━━━  4/17 [nvidia-nccl-cu12]
      Successfully uninstalled nvidia-curand-cu12-10.3.2.106━━  4/17 [nvidia-nccl-cu12]
  Attempting uninstall: nvidia-cufft-cu12━━━━━━━━━━━━━━━━━━━━━━━━━  5/17 [nvidia-curand-cu12]
   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/17 [nvidia-curand-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cufft-cu12 11.0.2.54
    Uninstalling nvidia-cufft-cu12-11.0.2.54:━━━━━━━━━━━━━━━━━  5/17 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cufft-cu12-11.0.2.54━━━━  5/17 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-runtime-cu12━━━━━━━━━━━━━━━━━━  6/17 [nvidia-cufft-cu12]
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━  6/17 [nvidia-cufft-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-runtime-cu12 12.1.105
    Uninstalling nvidia-cuda-runtime-cu12-12.1.105:━━━━━━━━━━━  6/17 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.1.1050m  6/17 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cuda-nvrtc-cu12━━━━━━━━━━━━━━━━  6/17 [nvidia-cufft-cu12]
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.1.1050m  6/17 [nvidia-cufft-cu12]
    Uninstalling nvidia-cuda-nvrtc-cu12-12.1.105:━━━━━━━━━━━━━  6/17 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.1.105  6/17 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cuda-cupti-cu12━━━━━━━━━━━━━━━━━━━━  8/17 [nvidia-cuda-nvrtc-cu12]
   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━  8/17 [nvidia-cuda-nvrtc-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-cupti-cu12 12.1.105
    Uninstalling nvidia-cuda-cupti-cu12-12.1.105:━━━━━━━━━━━━━  8/17 [nvidia-cuda-nvrtc-cu12]
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.1.105  8/17 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cublas-cu12m━━━━━━━━━━━━━━━━━━  9/17 [nvidia-cuda-cupti-cu12]
    Found existing installation: nvidia-cublas-cu12 12.1.3.1━━━━━━ 10/17 [nvidia-cublas-cu12]
    Uninstalling nvidia-cublas-cu12-12.1.3.1:m━━━━━━━━━━━━━━━━ 10/17 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cublas-cu12-12.1.3.1━━━━ 10/17 [nvidia-cublas-cu12]
  Attempting uninstall: nvidia-cusparse-cu12m━━━━━━━━━━━━━━━━ 10/17 [nvidia-cublas-cu12]
    Found existing installation: nvidia-cusparse-cu12 12.1.0.1060m 10/17 [nvidia-cublas-cu12]
    Uninstalling nvidia-cusparse-cu12-12.1.0.106:━━━━━━━━━━━━━ 10/17 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cusparse-cu12-12.1.0.106 10/17 [nvidia-cublas-cu12]
  Attempting uninstall: huggingface-hub91m╸━━━━━━━━━━━━━━ 11/17 [nvidia-cusparse-cu12]
    Found existing installation: huggingface_hub 1.7.1━━━━━━━━ 11/17 [nvidia-cusparse-cu12]
    Uninstalling huggingface_hub-1.7.1:━━━━━━━━━━━━━━ 11/17 [nvidia-cusparse-cu12]
      Successfully uninstalled huggingface_hub-1.7.190m━━━━━━━━━━━ 12/17 [huggingface-hub]]
  Attempting uninstall: tokenizers━━╺━━━━━━━━━━━ 12/17 [huggingface-hub]
    Found existing installation: tokenizers 0.22.2m━━━━━━━━━━━ 12/17 [huggingface-hub]
    Uninstalling tokenizers-0.22.2:m╺━━━━━━━━━━━ 12/17 [huggingface-hub]
      Successfully uninstalled tokenizers-0.22.290m━━━━━━━━━━━ 12/17 [huggingface-hub]
  Attempting uninstall: nvidia-cusolver-cu1291m╸━━━━━━━━━ 13/17 [tokenizers]]
    Found existing installation: nvidia-cusolver-cu12 11.4.5.1070m 13/17 [tokenizers]
    Uninstalling nvidia-cusolver-cu12-11.4.5.107:[90m━━━━━━━━━ 13/17 [tokenizers]
      Successfully uninstalled nvidia-cusolver-cu12-11.4.5.107 13/17 [tokenizers]
  Attempting uninstall: transformers━━━━╸━━━━━━━ 14/17 [nvidia-cusolver-cu12]
    Found existing installation: transformers 5.3.0[90m━━━━━━━ 14/17 [nvidia-cusolver-cu12]
    Uninstalling transformers-5.3.0:━━━━━━━╺━━━━ 15/17 [transformers]u12]
      Successfully uninstalled transformers-5.3.0━━━━ 15/17 [transformers]
  Attempting uninstall: torch━━━━━━━━━━━━━━╺━━━━ 15/17 [transformers]
    Found existing installation: torch 2.4.1[90m╺━━━━ 15/17 [transformers]
    Uninstalling torch-2.4.1:━━━━━━━━━━━━━━━━╸━━ 16/17 [torch]rs]
      Successfully uninstalled torch-2.4.1━━━╸━━ 16/17 [torch]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 [torch]m16/17 [torch]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.35 requires torch>=2.10, but you have torch 2.5.0 which is incompatible.
trl 0.29.0 requires transformers>=4.56.2, but you have transformers 4.45.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Successfully installed huggingface-hub-0.36.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 sympy-1.13.1 tokenizers-0.20.3 torch-2.5.0 transformers-4.45.0 triton-3.1.0

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [7]:
%pip install mlflow dagshub datasets peft bitsandbytes trl accelerate

WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Requirement already satisfied: mlflow in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (3.10.1)
Requirement already satisfied: dagshub in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.6.8)
Requirement already satisfied: datasets in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (4.7.0)
Requirement already satisfied: peft in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.18.1)
Requirement already satisfied: bitsandbytes in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.49.2)
Requirement already satisfied: trl in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.29.0)
Requirement already satisfied: accelerate in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (1.13.0)
Requirement already satisfied: mlflow-skinny==3.10.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (3.10.1)
Requirement already satisfied: mlflow-tracing==3.10.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (3.10.1)
Requirement already satisfied: Flask-CORS<7 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (46.0.5)
Requirement already satisfied: docker<8,>=4.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (25.1.0)
Requirement already satisfied: huey<3,>=2.5.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (3.8.2)
Requirement already satisfied: numpy<3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (2.1.4)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (1.3.2)
Requirement already satisfied: scipy<2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (1.11.4)
Requirement already satisfied: skops<1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow) (2.0.48)
Requirement already satisfied: cachetools<8,>=5.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (7.0.5)
Requirement already satisfied: click<9,>=7.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (0.99.0)
Requirement already satisfied: fastapi<1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (0.128.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (1.40.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (1.40.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (1.40.0)
Requirement already satisfied: packaging<27 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (25.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (6.33.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from mlflow-skinny==3.10.1->mlflow) (0.40.0)
Requirement already satisfied: Mako in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (2.49.1)
Requirement already satisfied: urllib3>=1.26.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from Flask<4->mlflow) (3.1.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (12.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow) (0.61b0)
Requirement already satisfied: pytz>=2020.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (2026.1.4)
Requirement already satisfied: joblib>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: anyio<5,>=3.6.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (4.12.1)
Requirement already satisfied: h11>=0.8 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from uvicorn<1->mlflow-skinny==3.10.1->mlflow) (0.16.0)
Requirement already satisfied: appdirs>=1.4.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (14.3.2)
Requirement already satisfied: dacite~=1.6.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (3.3.1)
Requirement already satisfied: boto3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (1.42.42)
Requirement already satisfied: semver in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.1.12 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from dagshub) (0.1.16)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (3.20.3)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (0.4.0)
Requirement already satisfied: tqdm>=4.66.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.1.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets) (0.36.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: httpcore==1.* in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: psutil in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from peft) (7.2.2)
Requirement already satisfied: torch>=1.13.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from peft) (2.5.0)
Requirement already satisfied: transformers in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from peft) (4.45.0)
Requirement already satisfied: safetensors in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from peft) (0.7.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.1.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (80.10.2)
Requirement already satisfied: sympy==1.13.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.13.0->peft) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.13.0->peft) (1.3.0)
Collecting transformers (from peft)

In [8]:
%pip install xformers

WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Requirement already satisfied: xformers in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.0.35)
Collecting torch>=2.10 (from xformers)
  Using cached torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from xformers) (1.26.4)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (4.15.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (80.10.2)
Collecting sympy>=1.13.3 (from torch>=2.10->xformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (2026.1.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (12.9.4)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch>=2.10->xformers)
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch>=2.10->xformers)
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch>=2.10->xformers)
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch>=2.10->xformers)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch>=2.10->xformers)
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch>=2.10->xformers)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch>=2.10->xformers)
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch>=2.10->xformers)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch>=2.10->xformers)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (0.7.1)
Collecting nvidia-nccl-cu12==2.27.5 (from torch>=2.10->xformers)
  Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (3.4.5)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch>=2.10->xformers)
  Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch>=2.10->xformers)
  Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.10->xformers) (1.13.1.3)
Collecting triton==3.6.0 (from torch>=2.10->xformers)
  Using cached triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch>=2.10->xformers) (1.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.10->xformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch>=2.10->xformers) (3.0.3)
Using cached torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl (915.6 MB)
Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Using cached triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Installing collected packages: triton, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
  Attempting uninstall: triton
    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: triton 3.1.0
    Uninstalling triton-3.1.0:
      Successfully uninstalled triton-3.1.0
  Attempting uninstall: sympy━━━━━━━━━━━━━━━━━━━  0/15 [triton]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/15 [triton]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/15 [sympy]
      Successfully uninstalled sympy-1.13.1━━━━━━━━━━━━━━━━━━━━━━━  1/15 [sympy]
  Attempting uninstall: nvidia-nvtx-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  1/15 [sympy]
    Found existing installation: nvidia-nvtx-cu12 12.4.127━━━━  1/15 [sympy]
    Uninstalling nvidia-nvtx-cu12-12.4.127:━━━━━━━━━━━━━━━━━━━  1/15 [sympy]
      Successfully uninstalled nvidia-nvtx-cu12-12.4.127━━━━━━  1/15 [sympy]
  Attempting uninstall: nvidia-nvjitlink-cu12━━━━━━━━━━━━━━━━━  1/15 [sympy]
    Found existing installation: nvidia-nvjitlink-cu12 12.4.127[0m  1/15 [sympy]
    Uninstalling nvidia-nvjitlink-cu12-12.4.127:━━━━━━━━━━━━━━  1/15 [sympy]
      Successfully uninstalled nvidia-nvjitlink-cu12-12.4.127━  1/15 [sympy]
  Attempting uninstall: nvidia-nccl-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  3/15 [nvidia-nvjitlink-cu12]
    Found existing installation: nvidia-nccl-cu12 2.21.5━━━━━━  3/15 [nvidia-nvjitlink-cu12]
    Uninstalling nvidia-nccl-cu12-2.21.5:━━━━━━━━━━━━━━━━━━━━━  3/15 [nvidia-nvjitlink-cu12]
      Successfully uninstalled nvidia-nccl-cu12-2.21.5━━━━━━━━  3/15 [nvidia-nvjitlink-cu12]
  Attempting uninstall: nvidia-curand-cu12━━━━━━━━━━━━━━━━━━━━━━━━  4/15 [nvidia-nccl-cu12]]
    Found existing installation: nvidia-curand-cu12 10.3.5.147━━━━  5/15 [nvidia-curand-cu12]
    Uninstalling nvidia-curand-cu12-10.3.5.147:━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-curand-cu12-10.3.5.147━━  5/15 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-runtime-cu12━━━━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-runtime-cu12 12.4.127
    Uninstalling nvidia-cuda-runtime-cu12-12.4.127:━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.4.1270m  5/15 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-nvrtc-cu12━━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.4.1270m  5/15 [nvidia-curand-cu12]
    Uninstalling nvidia-cuda-nvrtc-cu12-12.4.127:━━━━━━━━━━━━━━━━━  7/15 [nvidia-cuda-nvrtc-cu12]
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.4.127  7/15 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cuda-cupti-cu12━━━━━━━━━━━━━━━━━━━━  7/15 [nvidia-cuda-nvrtc-cu12]
   ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━  7/15 [nvidia-cuda-nvrtc-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-cupti-cu12 12.4.127
    Uninstalling nvidia-cuda-cupti-cu12-12.4.127:━━━━━━━━━━━━━  7/15 [nvidia-cuda-nvrtc-cu12]
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.4.127  7/15 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cublas-cu12m━━━━━━━━━━━━━━━━━━  8/15 [nvidia-cuda-cupti-cu12]
    Found existing installation: nvidia-cublas-cu12 12.4.5.8━━  8/15 [nvidia-cuda-cupti-cu12]
    Uninstalling nvidia-cublas-cu12-12.4.5.8:━━━━━━━━━━━━━━━━━  8/15 [nvidia-cuda-cupti-cu12]
      Successfully uninstalled nvidia-cublas-cu12-12.4.5.8━━━━  8/15 [nvidia-cuda-cupti-cu12]
  Attempting uninstall: nvidia-cusparse-cu120m━━━━━━━━━━━━━━━  9/15 [nvidia-cublas-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━  9/15 [nvidia-cublas-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cusparse-cu12 12.3.1.170
    Uninstalling nvidia-cusparse-cu12-12.3.1.170:━━━━━━━━━━━━━  9/15 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cusparse-cu12-12.3.1.170  9/15 [nvidia-cublas-cu12]
  Attempting uninstall: nvidia-cufft-cu121m╸━━━━━━━━━━━━━ 10/15 [nvidia-cusparse-cu12]
    Found existing installation: nvidia-cufft-cu12 11.2.1.3━━━ 10/15 [nvidia-cusparse-cu12]
    Uninstalling nvidia-cufft-cu12-11.2.1.3:0m╺━━━━━━━━━━ 11/15 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cufft-cu12-11.2.1.3━━━━━ 11/15 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cudnn-cu12╺━━━━━━━━━━ 11/15 [nvidia-cufft-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 11/15 [nvidia-cufft-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cudnn-cu12 9.1.0.70
    Uninstalling nvidia-cudnn-cu12-9.1.0.70:[0m━━━━━━━━━━ 11/15 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cudnn-cu12-9.1.0.70━━━━━ 11/15 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cusolver-cu12╺━━━━━━━ 12/15 [nvidia-cudnn-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 12/15 [nvidia-cudnn-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cusolver-cu12 11.6.1.9
    Uninstalling nvidia-cusolver-cu12-11.6.1.9:[0m━━━━━━━ 12/15 [nvidia-cudnn-cu12]
      Successfully uninstalled nvidia-cusolver-cu12-11.6.1.9━━ 12/15 [nvidia-cudnn-cu12]
  Attempting uninstall: torch━━━━━━━━━━━━━╸━━━━━ 13/15 [nvidia-cusolver-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 13/15 [nvidia-cusolver-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: torch 2.5.0
    Uninstalling torch-2.5.0:━━━━━━━━━━━━━━━━╺━━ 14/15 [torch]olver-cu12]
      Successfully uninstalled torch-2.5.0━━━╺━━ 14/15 [torch]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [torch]m14/15 [torch]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.20.0 requires torch==2.5.0, but you have torch 2.10.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Successfully installed nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-nccl-cu12-2.27.5 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvtx-cu12-12.8.90 sympy-1.14.0 torch-2.10.0 triton-3.6.0

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
# !pip uninstall torchvision -y
!pip install torchvision==0.19.1

WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Collecting torchvision==0.19.1
  Using cached torchvision-0.19.1-cp312-cp312-manylinux1_x86_64.whl.metadata (6.0 kB)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torchvision==0.19.1) (1.26.4)
Collecting torch==2.4.1 (from torchvision==0.19.1)
  Using cached torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torchvision==0.19.1) (12.1.0)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (3.20.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (4.15.0)
Requirement already satisfied: sympy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (1.14.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (3.1.6)
Requirement already satisfied: fsspec in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (2026.1.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch==2.4.1->torchvision==0.19.1) (80.10.2)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.4.1->torchvision==0.19.1)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.0.0 (from torch==2.4.1->torchvision==0.19.1)
  Using cached triton-3.0.0-1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.4.1->torchvision==0.19.1) (12.8.93)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch==2.4.1->torchvision==0.19.1) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy->torch==2.4.1->torchvision==0.19.1) (1.3.0)
Using cached torchvision-0.19.1-cp312-cp312-manylinux1_x86_64.whl (7.0 MB)
Using cached torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl (797.0 MB)
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Using cached triton-3.0.0-1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (209.5 MB)
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, nvidia-cudnn-cu12, torch, torchvision
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: nvidia-nvtx-cu12━━━━━━━━  0/14 [triton]
    Found existing installation: nvidia-nvtx-cu12 12.8.9014 [triton]
    Uninstalling nvidia-nvtx-cu12-12.8.90:━━━━━━━━━━━━━━━━━━━━━━━━  1/14 [nvidia-nvtx-cu12]
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90━━━━━━━  1/14 [nvidia-nvtx-cu12]
  Attempting uninstall: nvidia-nccl-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  1/14 [nvidia-nvtx-cu12]
    Found existing installation: nvidia-nccl-cu12 2.27.5━━━━━━  1/14 [nvidia-nvtx-cu12]
    Uninstalling nvidia-nccl-cu12-2.27.5:━━━━━━━━━━━━━━━━━━━━━  1/14 [nvidia-nvtx-cu12]
      Successfully uninstalled nvidia-nccl-cu12-2.27.5━━━━━━━━  1/14 [nvidia-nvtx-cu12]
  Attempting uninstall: nvidia-cusparse-cu12━━━━━━━━━━━━━━━━━━━━━━  2/14 [nvidia-nccl-cu12]
    Found existing installation: nvidia-cusparse-cu12 12.5.8.93[0m  2/14 [nvidia-nccl-cu12]
    Uninstalling nvidia-cusparse-cu12-12.5.8.93:━━━━━━━━━━━━━━  2/14 [nvidia-nccl-cu12]
      Successfully uninstalled nvidia-cusparse-cu12-12.5.8.93━  2/14 [nvidia-nccl-cu12]
  Attempting uninstall: nvidia-curand-cu12━━━━━━━━━━━━━━━━━━━━━━━━  3/14 [nvidia-cusparse-cu12]
    Found existing installation: nvidia-curand-cu12 10.3.9.90━  3/14 [nvidia-cusparse-cu12]
    Uninstalling nvidia-curand-cu12-10.3.9.90:━━━━━━━━━━━━━━━━  3/14 [nvidia-cusparse-cu12]
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90━━━  3/14 [nvidia-cusparse-cu12]
  Attempting uninstall: nvidia-cufft-cu12━━━━━━━━━━━━━━━━━━━━━━━━━  4/14 [nvidia-curand-cu12]
   ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/14 [nvidia-curand-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cufft-cu12 11.3.3.83
    Uninstalling nvidia-cufft-cu12-11.3.3.83:━━━━━━━━━━━━━━━━━  4/14 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.83━━━━  4/14 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cuda-runtime-cu12━━━━━━━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90[0m  5/14 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cuda-nvrtc-cu12━━━━━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]
   ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.93:━━━━━━━━━━━━━━  5/14 [nvidia-cufft-cu12]
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.93━  5/14 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cuda-cupti-cu12m━━━━━━━━━━━━━━━━━━━  7/14 [nvidia-cuda-nvrtc-cu12]
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.90[0m  7/14 [nvidia-cuda-nvrtc-cu12]
    Uninstalling nvidia-cuda-cupti-cu12-12.8.90:━━━━━━━━━━━━━━  7/14 [nvidia-cuda-nvrtc-cu12]
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.8.90━  7/14 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cublas-cu120m━━━━━━━━━━━━━━━━━  8/14 [nvidia-cuda-cupti-cu12]
    Found existing installation: nvidia-cublas-cu12 12.8.4.1━━  8/14 [nvidia-cuda-cupti-cu12]
    Uninstalling nvidia-cublas-cu12-12.8.4.1:━━━━━━━━━━━━━━━━━  8/14 [nvidia-cuda-cupti-cu12]
      Successfully uninstalled nvidia-cublas-cu12-12.8.4.1━━━━  8/14 [nvidia-cuda-cupti-cu12]
  Attempting uninstall: nvidia-cusolver-cu12[0m━━━━━━━━━━━━━━  9/14 [nvidia-cublas-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━  9/14 [nvidia-cublas-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: nvidia-cusolver-cu12 11.7.3.90
    Uninstalling nvidia-cusolver-cu12-11.7.3.90:━━━━━━━━━━━━━━  9/14 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cusolver-cu12-11.7.3.90━  9/14 [nvidia-cublas-cu12]
  Attempting uninstall: nvidia-cudnn-cu12[91m╸━━━━━━━━━━━ 10/14 [nvidia-cusolver-cu12]
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21━━ 10/14 [nvidia-cusolver-cu12]
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:m━━━━━━━━━━━ 10/14 [nvidia-cusolver-cu12]
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21━━━━ 10/14 [nvidia-cusolver-cu12]
  Attempting uninstall: torch━━━━━━━━━━╺━━━━━━━━ 11/14 [nvidia-cudnn-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 11/14 [nvidia-cudnn-cu12]    WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
    Found existing installation: torch 2.10.0
    Uninstalling torch-2.10.0:━━━━━━━━━━━━╺━━━━━ 12/14 [torch]nn-cu12]
      Successfully uninstalled torch-2.10.0[90m╺━━━━━ 12/14 [torch]
  Attempting uninstall: torchvision━━━━━━━╺━━━━━ 12/14 [torch]
    Found existing installation: torchvision 0.20.0m━━━━━ 12/14 [torch]
    Uninstalling torchvision-0.20.0:━━╺━━━━━ 12/14 [torch]
      Successfully uninstalled torchvision-0.20.0[0m━━━━━ 12/14 [torch]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/14 [torchvision] [torchvision]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.35 requires torch>=2.10, but you have torch 2.4.1 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages)
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvtx-cu12-12.1.105 torch-2.4.1 torchvision-0.19.1 triton-3.0.0

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

# **Configuration du projet `clinical-orientation-ai` sur `DagsHub`**

In [10]:
# Imports
import os
import mlflow
import dagshub
from dagshub.auth import add_app_token, get_token
from dotenv import load_dotenv

In [11]:
# Configuration pour l'organisation
ORGANIZATION_NAME = "Projet-Capstone-IA"
REPO_NAME = "clinical-orientation-ai"

In [12]:
load_dotenv()

DAGSHUB_TOKEN = os.getenv('DAGSHUB_TOKEN')
DAGSHUB_USERNAME = os.getenv('DAGSHUB_USERNAME')
DAGSHUB_REPO = os.getenv('DAGSHUB_REPO')

# Inclure le token dans l'URI pour l'authentification
TRACKING_URI = f"https://{DAGSHUB_USERNAME}:{DAGSHUB_TOKEN}@dagshub.com/{DAGSHUB_USERNAME}/{DAGSHUB_REPO}.mlflow"
mlflow.set_tracking_uri(TRACKING_URI)

print(f"MLflow configuré avec authentification")
print(f"URI: {TRACKING_URI.replace(DAGSHUB_TOKEN, '****')}")

MLflow configuré avec authentification
URI: https://kevin-tchinda:****@dagshub.com/kevin-tchinda/clinical-orientation-ai.mlflow

In [13]:
# Création de l'expérience MLflow
EXPERIMENT_NAME = "medquad-model-finetuning"

# mlflow.create_experiment(EXPERIMENT_NAME) # Already exist
mlflow.set_experiment(EXPERIMENT_NAME)

print(f"Expérience: {EXPERIMENT_NAME}")

Expérience: medquad-model-finetuning

## **Imports**

In [14]:
import torch
from transformers import (
    AutoModelForCausalLM, 
    AutoTokenizer, 
    TrainingArguments, 
    Trainer,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
import pandas as pd
import numpy as np
import pickle
from pathlib import Path
import random

import matplotlib.pyplot as plt
from mlflow.tracking import MlflowClient
import math
from tqdm import tqdm
# from xformers.ops import memory_efficient_attention

RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

In [9]:
# Vérifier le GPU disponible
print(f"GPU disponible: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"Nom du GPU: {torch.cuda.get_device_name(0)}")
    print(f"Mémoire totale: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"Mémoire disponible: {torch.cuda.memory_reserved(0) / 1e9:.2f} GB")
else:
    print("Attention: Pas de GPU détecté. L'entraînement sera très lent.")

GPU disponible: True
Nom du GPU: NVIDIA A100-SXM4-80GB
Mémoire totale: 85.29 GB
Mémoire disponible: 0.00 GB

## **Configurations des modèles à Entraîner**

In [15]:
models_config = [
    {
        "name": "microsoft/Phi-3.5-mini-instruct",
        "short_name": "phi-3.5-3.8B",
        "description": "Phi-3.5 mini instruct 3.8B - Microsoft",
        "lang": "fr/en",
        "context_length": 4096,
        "batch_size": 4,
        "gradient_accumulation": 4,
        "learning_rate": 2e-4,
        "lora_r": 16,
        "lora_alpha": 32
    },
    {
        "name": "meta-llama/Llama-3.2-3B-Instruct",
        "short_name": "llama-3.2-3B",
        "description": "Llama 3.2 3B Instruct - Meta",
        "lang": "fr/en",
        "context_length": 8192,
        "batch_size": 4,
        "gradient_accumulation": 4,
        "learning_rate": 2e-4,
        "lora_r": 16,
        "lora_alpha": 32
    }
]

print("Modèles :")
for i, config in enumerate(models_config):
    print(f"{i+1}. {config['name']} ({config['short_name']})")

Modèles :
1. microsoft/Phi-3.5-mini-instruct (phi-3.5-3.8B)
2. meta-llama/Llama-3.2-3B-Instruct (llama-3.2-3B)

In [17]:
# Changement de Serveur GPU
# Vérifier le GPU disponible
print(f"GPU disponible: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"Nom du GPU: {torch.cuda.get_device_name(0)}")
    print(f"Mémoire totale: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"Mémoire disponible: {torch.cuda.memory_reserved(0) / 1e9:.2f} GB")
else:
    print("Attention: Pas de GPU détecté. L'entraînement sera très lent.")

GPU disponible: True
Nom du GPU: NVIDIA L4
Mémoire totale: 23.92 GB
Mémoire disponible: 0.00 GB

## **Chargement des données**

In [18]:
# # Ajouter le chemin pour importer nos modules
import os
import sys

sys.path.append(os.path.abspath(".."))
# sys.path.append('clinical-orientation-ai')

# Importer notre classe Dataset
from utils.dataset import MedQADataset

print(f"Dataset importé avec succès: \n{MedQADataset}")

Dataset importé avec succès:
<class 'utils.dataset.MedQADataset'>

In [19]:
PROJET_ROOT = Path.cwd().parent
data_path = f"{PROJET_ROOT}/data"

with open(f"{data_path}/train_dataset.pkl", "rb") as f:
    train_dataset = pickle.load(f)
with open(f"{data_path}/val_dataset.pkl", "rb") as f:
    val_dataset = pickle.load(f)

print(f"Train: {len(train_dataset)} exemples")
print(f"Validation: {len(val_dataset)} exemples")

Train: 11494 exemples
Validation: 2431 exemples

In [20]:
# Connexion à HuggingFace
from huggingface_hub import login
login()

In [21]:
import gc
import torch

import gc
import torch

# Nettoyage sécurisé (sans pkill)
gc.collect()
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()
torch.cuda.reset_accumulated_memory_stats()

# # Vérifier la mémoire
# free_memory, total_memory = torch.cuda.mem_get_info()
# free_gb = free_memory / 1024**3
# total_gb = total_memory / 1024**3
# print(f"Mémoire GPU après nettoyage: {free_gb:.2f} GB libres / {total_gb:.2f} GB total")

# Optionnel: voir l'occupation sans tuer
import subprocess
subprocess.run(["nvidia-smi"])

Tue Mar 17 05:58:38 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.211.01             Driver Version: 570.211.01     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L4                      Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             16W /   72W |       3MiB /  23034MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

CompletedProcess(args=['nvidia-smi'], returncode=0)

## **Fonction d'entraînement avec `MLflow`**

In [22]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer, BitsAndBytesConfig, EarlyStoppingCallback
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

def train_model_with_mlflow(model_config, train_dataset, val_dataset):
    with mlflow.start_run(run_name=model_config["short_name"]):
        mlflow.log_params({
            "model_name": model_config["name"],
            "learning_rate": model_config["learning_rate"],
            "batch_size": model_config["batch_size"],
            "gradient_accumulation": model_config["gradient_accumulation"],
            "lora_r": model_config["lora_r"],
            "lora_alpha": model_config["lora_alpha"],
            "early_stopping_patience": 2,
            "num_epochs": 5
        })
        
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True
        )
        
        base_model = AutoModelForCausalLM.from_pretrained(
            model_config["name"],
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=torch.float16,
            trust_remote_code=True,
            # attn_implementation="flash_attention_2" # Use of flash_attn
        )
        
        tokenizer = AutoTokenizer.from_pretrained(model_config["name"])
        tokenizer.pad_token = tokenizer.eos_token
        
        model = prepare_model_for_kbit_training(base_model)
        
        lora_config = LoraConfig(
            r=model_config["lora_r"],
            lora_alpha=model_config["lora_alpha"],
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type="CAUSAL_LM"
        )
        
        model = get_peft_model(model, lora_config)
        
        # Calcul des steps (environ 718 steps par époque)
        steps_per_epoch = len(train_dataset) // (model_config["batch_size"] * model_config["gradient_accumulation"])
        eval_steps = max(1, steps_per_epoch // 4)  # ~180 steps
        save_steps = eval_steps
        
        training_args = TrainingArguments(
            output_dir=f"./results/{model_config['short_name']}",
            num_train_epochs=5,
            per_device_train_batch_size=model_config["batch_size"],
            per_device_eval_batch_size=model_config["batch_size"],
            gradient_accumulation_steps=model_config["gradient_accumulation"],
            warmup_ratio=0.1,
            logging_steps=50,
            eval_strategy="steps",
            eval_steps=eval_steps,
            save_steps=save_steps,
            save_total_limit=2,
            learning_rate=model_config["learning_rate"],
            fp16=True,
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
            report_to="none",
            remove_unused_columns=False,
            dataloader_num_workers=4,
            optim="paged_adamw_8bit"
        )
        
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=val_dataset,
            callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
        )
        
        trainer.train()
        
        eval_results = trainer.evaluate()
        mlflow.log_metrics({
            "final_eval_loss": eval_results["eval_loss"],
            "final_eval_perplexity": float(torch.exp(torch.tensor(eval_results["eval_loss"])))
        })
        
        model_path = f"./models/{model_config['short_name']}-final"
        trainer.save_model(model_path)
        tokenizer.save_pretrained(model_path)
        mlflow.log_artifacts(model_path, artifact_path="model")
        
        return trainer

## **Lancement des `Trains` sur  `Phi-3.5-mini-instruct-3.8B` et `Llama-3.2-3B-Instruct`**

In [23]:
# trainers = {}

# for config in models_config:
#     print(f"Entraînement de {config['short_name']}...")
#     trainer = train_model_with_mlflow(config, train_dataset, val_dataset)
#     trainers[config['short_name']] = trainer
#     print(f"{config['short_name']} terminé")

In [28]:
# Entraînement modèle 01
trainers = {}

# Modifier la configuration de MedGemma avant de relancer
# models_config[0].update({
#     "batch_size": 1,
#     "gradient_accumulation": 16
# })

config = models_config[0]
print(f"Entraînement de {config['short_name']}...")
trainer = train_model_with_mlflow(config, train_dataset, val_dataset)
trainers[config['short_name']] = trainer
print(f"{config['short_name']} terminé")

Entraînement de phi-3.5-3.8B...

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )

/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  )

🏃 View run phi-3.5-3.8B at: https://kevin-tchinda:5cc4bfd03a93147786a6c36448602dfa927dd70f@dagshub.com/kevin-tchinda/clinical-orientation-ai.mlflow/#/experiments/0/runs/0375b20edbdf4fc293a7296b7deeb215
🧪 View experiment at: https://kevin-tchinda:5cc4bfd03a93147786a6c36448602dfa927dd70f@dagshub.com/kevin-tchinda/clinical-orientation-ai.mlflow/#/experiments/0

RuntimeError: on_train_begin must be called before on_evaluate

## **Chargeons le meilleur `checkpoint` du Modèle `Phi-3.5-3.8B`**
NB: Le Trainer a sauvegardé les checkpoints dans ./results/phi-3.5-3.8B. On charge le dernier (ou le meilleur) avec load_best_model_at_end=True.

In [42]:
# Chemin vers les résultats
model_path = "./results/phi-3.5-3.8B/checkpoint-3580"  # dernier step
# ou laisser le Trainer choisir le meilleur : model_path = "./results/phi-3.5-3.8B"

model_phi = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype=torch.float16
)
tokenizer_phi = AutoTokenizer.from_pretrained(models_config[0]["name"])

print("Modèle chargé")

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/64 [00:00<?, ?it/s]

Modèle chargé

## **Évaluation de `Phi-3.5-3.8B` sur le `Test Set`**

In [28]:
with open(f"{data_path}/test_dataset.pkl", "rb") as f:
    test_dataset = pickle.load(f)

model_phi.eval()
total_loss = 0
total_tokens = 0
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=4, shuffle=False)

with torch.no_grad():
    for batch in tqdm(test_loader, desc="Évaluation test"):
        input_ids = batch['input_ids'].to(model_phi.device)
        attention_mask = batch['attention_mask'].to(model_phi.device)
        labels = batch['labels'].to(model_phi.device)

        outputs = model_phi(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss

        batch_tokens = (labels != -100).sum().item()
        total_loss += loss.item() * batch_tokens
        total_tokens += batch_tokens

avg_loss = total_loss / total_tokens
perplexity = math.exp(avg_loss)

Évaluation test: 100%|██████████| 609/609 [04:06<00:00,  2.47it/s]

In [29]:
# Affichage des résultats
print(f"Test Loss: {avg_loss:.4f}")
print(f"Test Perplexity: {perplexity:.2f}")

Test Loss: 10.7010
Test Perplexity: 44401.96

## **Enregistrement des métriques de `Phi-3.5-3.8B` dans `MLflow`**

In [32]:
# with mlflow.start_run(run_name="phi-3.5-3.8B"):
#     mlflow.log_metrics({
#         "test_loss": avg_loss,
#         "test_perplexity": perplexity
#     })

#     mlflow.pytorch.log_model(model_phi, "phi-3.5-3.8B__v2")


with mlflow.start_run(run_name="phi-3.5-3.8B"):
    # Log des métriques
    mlflow.log_metrics({
        "test_loss": avg_loss,
        "test_perplexity": perplexity
    })
    
    # Sauvegarder le modèle et le tokenizer dans un dossier local
    local_model_path = "../models/phi-3.5-3.8B_v2"
    model_phi.save_pretrained(local_model_path)
    tokenizer_phi.save_pretrained(local_model_path)
    
    # Enregistrer tout le dossier comme artefact MLflow
    mlflow.log_artifacts(local_model_path, artifact_path="model")
    
    # Optionnel : ajouter un fichier README avec les infos
    with open("model_info.txt", "w") as f:
        f.write(f"Model: phi-3.5-3.8B\n")
        f.write(f"Test loss: {avg_loss:.4f}\n")
        f.write(f"Test perplexity: {perplexity:.2f}\n")
        f.write(f"Local path: {local_model_path}\n")
    mlflow.log_artifact("model_info.txt")
    
    # Nettoyage (facultatif) : supprimer le dossier local après upload
    # shutil.rmtree(local_model_path)
    
    print("Modèle enregistré comme artefact dans MLflow.")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modèle enregistré comme artefact dans MLflow.
🏃 View run phi-3.5-3.8B at: https://kevin-tchinda:5cc4bfd03a93147786a6c36448602dfa927dd70f@dagshub.com/kevin-tchinda/clinical-orientation-ai.mlflow/#/experiments/0/runs/bd84f9b34ed7444d8c73949702de3256
🧪 View experiment at: https://kevin-tchinda:5cc4bfd03a93147786a6c36448602dfa927dd70f@dagshub.com/kevin-tchinda/clinical-orientation-ai.mlflow/#/experiments/0

## **Aperću des réponses du Modèle `Phi-3.5-3.8B`**

In [33]:
# Fonction de génération de reponses:
def generate_response(question, model, tokenizer, max_length=256):
    prompt = f"<s>[INST] {question} [/INST]"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.1,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )
    
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.split("[/INST]")[-1].strip()
    return response

In [39]:
# Charger les données de tests
test_df = pd.read_csv(f"{PROJET_ROOT}/data/test.csv")
print(f"Test: {len(test_df)} exemples")

# Aperçu
print("\nAperçu des données:")
test_df[-5:]

Test: 2434 exemples

Aperçu des données:

,question,answer,source,focus_area,question_len,answer_len
2429,What is (are) Diabetic Neuropathies: The Nerve...,"Peripheral neuropathy, also called distal symm...",NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...,67,1190
2430,What is (are) Diabetic Neuropathies: The Nerve...,Autonomic neuropathy affects the nerves that c...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...,67,3443
2431,What is (are) Diabetic Neuropathies: The Nerve...,"Proximal neuropathy, sometimes called lumbosac...",NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...,67,561
2432,What is (are) Diabetic Neuropathies: The Nerve...,Focal neuropathy appears suddenly and affects ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...,67,1120
2433,What are the treatments for Diabetic Neuropath...,The first treatment step is to bring blood glu...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...,81,7725

In [43]:
# Prendre un exemple du test set
sample = test_df.iloc[0]
question = sample['question']
true_focus = sample['focus_area']
true_answer = sample['answer']

generated = generate_response(question, model_phi, tokenizer_phi)

In [44]:
print(f"Question: {question}")
print(f"Focus area réel: {true_focus}")
print(f"\nRéponse générée ( ):")
print(generated[:])
print(f"\nRéponse attendue ( ):")
print(true_answer[:])

Question: What is (are) Glaucoma ?
Focus area réel: Glaucoma

Réponse générée ( ):
Glaucoma is a group of eye conditions that damage the optic nerve, which is vital for good vision. This damage is often caused by abnormally high pressure in your eye. Glaucoma is one of the leading causes of blindness for people over the age of 60.

Here are some key points about glaucoma:

1. **Types**: There are several types of glaucoma, but the two main ones are:
   - **Open-angle glaucoma**: This is the most common form and occurs gradually, where the eye does not drain fluid as well as it should.
   - **Angle-closure glaucoma**: This type occurs when the iris bulges forward to narrow or block the drainage angle formed by the cornea and iris. As a result, fluid pressure inside the eye increases.

2. **Symptoms**: In its early stages, glaucoma typically has no symptoms. As the condition progresses, it can lead to loss of peripheral (side) vision, which can eventually become severe and lead to tunnel vision.

3. **Risk Factors**

Réponse attendue ( ):
Glaucoma is a group of diseases that can damage the eye's optic nerve and result in vision loss and blindness. While glaucoma can strike anyone, the risk is much greater for people over 60. How Glaucoma Develops  There are several different types of glaucoma. Most of these involve the drainage system within the eye. At the front of the eye there is a small space called the anterior chamber. A clear fluid flows through this chamber and bathes and nourishes the nearby tissues. (Watch the video to learn more about glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) In glaucoma, for still unknown reasons, the fluid drains too slowly out of the eye. As the fluid builds up, the pressure inside the eye rises. Unless this pressure is controlled, it may cause damage to the optic nerve and other parts of the eye and result in loss of vision. Open-angle Glaucoma The most common type of glaucoma is called open-angle glaucoma. In the normal eye, the clear fluid leaves the anterior chamber at the open angle where the cornea and iris meet. When fluid reaches the angle, it flows through a spongy meshwork, like a drain, and leaves the eye. Sometimes, when the fluid reaches the angle, it passes too slowly through the meshwork drain, causing the pressure inside the eye to build. If the pressure damages the optic nerve, open-angle glaucoma -- and vision loss -- may result. There is no cure for glaucoma. Vision lost from the disease cannot be restored. However, there are treatments that may save remaining vision. That is why early diagnosis is important.  See this graphic for a quick overview of glaucoma,  including how many people it affects, whos at risk, what to do if you have it, and how to learn more.  See a glossary of glaucoma terms.

In [48]:
# On souhaite que le LLM puisse reconnaitre le contexte clinique:
question_ouverte = "Bonjour"
reponse_generee = generate_response(question_ouverte, model_phi, tokenizer_phi)

print(f"Question: {question_ouverte}")
print(generated[:])

Question: Bonjour
Glaucoma is a group of eye conditions that damage the optic nerve, which is vital for good vision. This damage is often caused by abnormally high pressure in your eye. Glaucoma is one of the leading causes of blindness for people over the age of 60.

Here are some key points about glaucoma:

1. **Types**: There are several types of glaucoma, but the two main ones are:
   - **Open-angle glaucoma**: This is the most common form and occurs gradually, where the eye does not drain fluid as well as it should.
   - **Angle-closure glaucoma**: This type occurs when the iris bulges forward to narrow or block the drainage angle formed by the cornea and iris. As a result, fluid pressure inside the eye increases.

2. **Symptoms**: In its early stages, glaucoma typically has no symptoms. As the condition progresses, it can lead to loss of peripheral (side) vision, which can eventually become severe and lead to tunnel vision.

3. **Risk Factors**

## **Observation sur le comportement de `Phi-3.5-3.8B` fine-tuné**

- Le modèle `phi-3.5-3.8B` fine-tuné sur MedQuAD répond correctement et de manière structurée aux questions médicales (exemple : "What is glaucoma ?").  
Cependant, il présente un **oubli catastrophique** de ses capacités conversationnelles générales : une simple salutation ("Bonjour") déclenche également une réponse détaillée sur le glaucome, sans aucune adaptation au contexte dialogique.  

- Ce comportement montre que le modèle a sur-appris le domaine médical au détriment des interactions sociales de base. Pour l'usage final (agent conversationnel exploratoire), il sera nécessaire de réaliser un **instruction tuning** avec un mélange de données générales et médicales afin de préserver les compétences conversationnelles tout en maintenant la pertinence clinique.

---

---

---

In [ ]:
# Entraînement modèle 02
config = models_config[1]
print(f"Entraînement de {config['short_name']}...")
trainer = train_model_with_mlflow(config, train_dataset, val_dataset)
trainers[config['short_name']] = trainer
print(f"{config['short_name']} terminé")

## **Visualization des courbes d'apprentissages**

In [ ]:
import matplotlib.pyplot as plt
from mlflow.tracking import MlflowClient

client = MlflowClient()
experiment = client.get_experiment_by_name("medquad-model-finetuning")
runs = client.search_runs(experiment_ids=[experiment.experiment_id])

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

for run in runs:
    run_name = run.data.tags.get("mlflow.runName", "unknown")
    history = client.get_metric_history(run.info.run_id, "eval_loss")
    steps = [m.step for m in history]
    values = [m.value for m in history]
    axes[0].plot(steps, values, label=run_name)

axes[0].set_xlabel("Step")
axes[0].set_ylabel("Eval Loss")
axes[0].set_title("Courbes de validation loss")
axes[0].legend()
axes[0].grid(True)

for run in runs:
    run_name = run.data.tags.get("mlflow.runName", "unknown")
    history = client.get_metric_history(run.info.run_id, "eval_loss")
    steps = [m.step for m in history]
    values = [m.value for m in history]
    perplexities = [float(torch.exp(torch.tensor(v))) for v in values]
    axes[1].plot(steps, perplexities, label=run_name)

axes[1].set_xlabel("Step")
axes[1].set_ylabel("Perplexity")
axes[1].set_title("Courbes de perplexité")
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

## **Évaluation des modèles sur le `Test` set**

In [ ]:
import math
from tqdm import tqdm

In [ ]:
# Charger les données de test
test_path = f"{data_path}/test_dataset.pkl"
with open(test_path, "rb") as f:
    test_dataset = pickle.load(f)

In [ ]:
# Fonction d'évaluation de modèle
def evaluate_model(model, test_dataset):
    model.eval()
    total_loss = 0
    total_tokens = 0
    
    test_loader = torch.utils.data.DataLoader(
        test_dataset, 
        batch_size=4, 
        shuffle=False
    )
    
    with torch.no_grad():
        for batch in tqdm(test_loader, desc="Évaluation"):
            input_ids = batch['input_ids'].to(model.device)
            attention_mask = batch['attention_mask'].to(model.device)
            labels = batch['labels'].to(model.device)
            
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            
            batch_tokens = (labels != -100).sum().item()
            total_loss += loss.item() * batch_tokens
            total_tokens += batch_tokens
    
    avg_loss = total_loss / total_tokens
    perplexity = math.exp(avg_loss)
    
    return {"loss": avg_loss, "perplexity": perplexity}

In [ ]:
evaluation_results = {}

for name, trainer in trainers.items():
    print(f"Évaluation de {name}...")
    results = evaluate_model(trainer.model, test_dataset)
    evaluation_results[name] = results
    print(f"Loss: {results['loss']:.4f}, Perplexity: {results['perplexity']:.2f}")
    
    with mlflow.start_run(run_name=f"{name}_evaluation"):
        mlflow.log_metrics({
            f"{name}_test_loss": results['loss'],
            f"{name}_test_perplexity": results['perplexity']
        })